// Package apis provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package apis

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// GetApiNowTableTableNameParams defines parameters for GetApiNowTableTableName.
type GetApiNowTableTableNameParams struct {
	// SysparmQuery An encoded query string used to filter the results
	SysparmQuery *interface{} `form:"sysparm_query,omitempty" json:"sysparm_query,omitempty"`

	// SysparmDisplayValue Return field display values (true), actual values (false), or both (all) (default: false)
	SysparmDisplayValue *interface{} `form:"sysparm_display_value,omitempty" json:"sysparm_display_value,omitempty"`

	// SysparmExcludeReferenceLink True to exclude Table API links for reference fields (default: false)
	SysparmExcludeReferenceLink *interface{} `form:"sysparm_exclude_reference_link,omitempty" json:"sysparm_exclude_reference_link,omitempty"`

	// SysparmSuppressPaginationHeader True to supress pagination header (default: false)
	SysparmSuppressPaginationHeader *interface{} `form:"sysparm_suppress_pagination_header,omitempty" json:"sysparm_suppress_pagination_header,omitempty"`

	// SysparmFields A comma-separated list of fields to return in the response
	SysparmFields *interface{} `form:"sysparm_fields,omitempty" json:"sysparm_fields,omitempty"`

	// SysparmLimit The maximum number of results returned per page (default: 10,000)
	SysparmLimit *interface{} `form:"sysparm_limit,omitempty" json:"sysparm_limit,omitempty"`

	// SysparmView Render the response according to the specified UI view (overridden by sysparm_fields)
	SysparmView *interface{} `form:"sysparm_view,omitempty" json:"sysparm_view,omitempty"`

	// SysparmQueryCategory Name of the query category (read replica category) to use for queries
	SysparmQueryCategory *interface{} `form:"sysparm_query_category,omitempty" json:"sysparm_query_category,omitempty"`

	// SysparmQueryNoDomain True to access data across domains if authorized (default: false)
	SysparmQueryNoDomain *interface{} `form:"sysparm_query_no_domain,omitempty" json:"sysparm_query_no_domain,omitempty"`

	// SysparmNoCount Do not execute a select count(*) on table (default: false)
	SysparmNoCount *interface{} `form:"sysparm_no_count,omitempty" json:"sysparm_no_count,omitempty"`
}

// PostApiNowTableTableNameJSONBody defines parameters for PostApiNowTableTableName.
type PostApiNowTableTableNameJSONBody interface{}

// PostApiNowTableTableNameParams defines parameters for PostApiNowTableTableName.
type PostApiNowTableTableNameParams struct {
	// SysparmDisplayValue Return field display values (true), actual values (false), or both (all) (default: false)
	SysparmDisplayValue *interface{} `form:"sysparm_display_value,omitempty" json:"sysparm_display_value,omitempty"`

	// SysparmExcludeReferenceLink True to exclude Table API links for reference fields (default: false)
	SysparmExcludeReferenceLink *interface{} `form:"sysparm_exclude_reference_link,omitempty" json:"sysparm_exclude_reference_link,omitempty"`

	// SysparmFields A comma-separated list of fields to return in the response
	SysparmFields *interface{} `form:"sysparm_fields,omitempty" json:"sysparm_fields,omitempty"`

	// SysparmInputDisplayValue Set field values using their display value (true) or actual value (false) (default: false)
	SysparmInputDisplayValue *interface{} `form:"sysparm_input_display_value,omitempty" json:"sysparm_input_display_value,omitempty"`

	// SysparmSuppressAutoSysField True to suppress auto generation of system fields (default: false)
	SysparmSuppressAutoSysField *interface{} `form:"sysparm_suppress_auto_sys_field,omitempty" json:"sysparm_suppress_auto_sys_field,omitempty"`

	// SysparmView Render the response according to the specified UI view (overridden by sysparm_fields)
	SysparmView *interface{} `form:"sysparm_view,omitempty" json:"sysparm_view,omitempty"`
}

// DeleteApiNowTableTableNameSysIdParams defines parameters for DeleteApiNowTableTableNameSysId.
type DeleteApiNowTableTableNameSysIdParams struct {
	// SysparmQueryNoDomain True to access data across domains if authorized (default: false)
	SysparmQueryNoDomain *interface{} `form:"sysparm_query_no_domain,omitempty" json:"sysparm_query_no_domain,omitempty"`
}

// GetApiNowTableTableNameSysIdParams defines parameters for GetApiNowTableTableNameSysId.
type GetApiNowTableTableNameSysIdParams struct {
	// SysparmDisplayValue Return field display values (true), actual values (false), or both (all) (default: false)
	SysparmDisplayValue *interface{} `form:"sysparm_display_value,omitempty" json:"sysparm_display_value,omitempty"`

	// SysparmExcludeReferenceLink True to exclude Table API links for reference fields (default: false)
	SysparmExcludeReferenceLink *interface{} `form:"sysparm_exclude_reference_link,omitempty" json:"sysparm_exclude_reference_link,omitempty"`

	// SysparmFields A comma-separated list of fields to return in the response
	SysparmFields *interface{} `form:"sysparm_fields,omitempty" json:"sysparm_fields,omitempty"`

	// SysparmView Render the response according to the specified UI view (overridden by sysparm_fields)
	SysparmView *interface{} `form:"sysparm_view,omitempty" json:"sysparm_view,omitempty"`

	// SysparmQueryNoDomain True to access data across domains if authorized (default: false)
	SysparmQueryNoDomain *interface{} `form:"sysparm_query_no_domain,omitempty" json:"sysparm_query_no_domain,omitempty"`
}

// PatchApiNowTableTableNameSysIdJSONBody defines parameters for PatchApiNowTableTableNameSysId.
type PatchApiNowTableTableNameSysIdJSONBody interface{}

// PatchApiNowTableTableNameSysIdParams defines parameters for PatchApiNowTableTableNameSysId.
type PatchApiNowTableTableNameSysIdParams struct {
	// SysparmDisplayValue Return field display values (true), actual values (false), or both (all) (default: false)
	SysparmDisplayValue *interface{} `form:"sysparm_display_value,omitempty" json:"sysparm_display_value,omitempty"`

	// SysparmExcludeReferenceLink True to exclude Table API links for reference fields (default: false)
	SysparmExcludeReferenceLink *interface{} `form:"sysparm_exclude_reference_link,omitempty" json:"sysparm_exclude_reference_link,omitempty"`

	// SysparmFields A comma-separated list of fields to return in the response
	SysparmFields *interface{} `form:"sysparm_fields,omitempty" json:"sysparm_fields,omitempty"`

	// SysparmInputDisplayValue Set field values using their display value (true) or actual value (false) (default: false)
	SysparmInputDisplayValue *interface{} `form:"sysparm_input_display_value,omitempty" json:"sysparm_input_display_value,omitempty"`

	// SysparmSuppressAutoSysField True to suppress auto generation of system fields (default: false)
	SysparmSuppressAutoSysField *interface{} `form:"sysparm_suppress_auto_sys_field,omitempty" json:"sysparm_suppress_auto_sys_field,omitempty"`

	// SysparmView Render the response according to the specified UI view (overridden by sysparm_fields)
	SysparmView *interface{} `form:"sysparm_view,omitempty" json:"sysparm_view,omitempty"`

	// SysparmQueryNoDomain True to access data across domains if authorized (default: false)
	SysparmQueryNoDomain *interface{} `form:"sysparm_query_no_domain,omitempty" json:"sysparm_query_no_domain,omitempty"`
}

// PutApiNowTableTableNameSysIdJSONBody defines parameters for PutApiNowTableTableNameSysId.
type PutApiNowTableTableNameSysIdJSONBody interface{}

// PutApiNowTableTableNameSysIdParams defines parameters for PutApiNowTableTableNameSysId.
type PutApiNowTableTableNameSysIdParams struct {
	// SysparmDisplayValue Return field display values (true), actual values (false), or both (all) (default: false)
	SysparmDisplayValue *interface{} `form:"sysparm_display_value,omitempty" json:"sysparm_display_value,omitempty"`

	// SysparmExcludeReferenceLink True to exclude Table API links for reference fields (default: false)
	SysparmExcludeReferenceLink *interface{} `form:"sysparm_exclude_reference_link,omitempty" json:"sysparm_exclude_reference_link,omitempty"`

	// SysparmFields A comma-separated list of fields to return in the response
	SysparmFields *interface{} `form:"sysparm_fields,omitempty" json:"sysparm_fields,omitempty"`

	// SysparmInputDisplayValue Set field values using their display value (true) or actual value (false) (default: false)
	SysparmInputDisplayValue *interface{} `form:"sysparm_input_display_value,omitempty" json:"sysparm_input_display_value,omitempty"`

	// SysparmSuppressAutoSysField True to suppress auto generation of system fields (default: false)
	SysparmSuppressAutoSysField *interface{} `form:"sysparm_suppress_auto_sys_field,omitempty" json:"sysparm_suppress_auto_sys_field,omitempty"`

	// SysparmView Render the response according to the specified UI view (overridden by sysparm_fields)
	SysparmView *interface{} `form:"sysparm_view,omitempty" json:"sysparm_view,omitempty"`

	// SysparmQueryNoDomain True to access data across domains if authorized (default: false)
	SysparmQueryNoDomain *interface{} `form:"sysparm_query_no_domain,omitempty" json:"sysparm_query_no_domain,omitempty"`
}

// PostApiNowTableTableNameJSONRequestBody defines body for PostApiNowTableTableName for application/json ContentType.
type PostApiNowTableTableNameJSONRequestBody PostApiNowTableTableNameJSONBody

// PatchApiNowTableTableNameSysIdJSONRequestBody defines body for PatchApiNowTableTableNameSysId for application/json ContentType.
type PatchApiNowTableTableNameSysIdJSONRequestBody PatchApiNowTableTableNameSysIdJSONBody

// PutApiNowTableTableNameSysIdJSONRequestBody defines body for PutApiNowTableTableNameSysId for application/json ContentType.
type PutApiNowTableTableNameSysIdJSONRequestBody PutApiNowTableTableNameSysIdJSONBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTW8bNxD9KwOe5GJtKe1tgaJw7aL1oUHgj1NhCDQ5a7Hhkgw5lKUK+9+L4Ur+iD9k",
	"xYEdAzrJ5i7fPM4M3yOlhcAZYXTSHnqVRL0QOVpRiwlRSPVwqL1Kewnj1Ch0/mpP+Xb4m/KOcEa/Hpz8",
	"hTbUx3+cnO6eyguLu/ufjkRXCeMaz1gak4omkPFO1GLfWn+VYO4zkIeAsfGxBRVRElYQUeoKctCSEKTT",
	"oNEiIQwOjs8Od8AHjJKBEngHODOJjLsE4rBJVIIMWRS1KDyAeVRiijH1oa0kTMTUfEAngxG1+GVvtPdB",
	"VCJImpSVD2UwQ+evhgV0uCgfH2WLHT+9RLq/pGOkaHCKEFH5qBM00bcge1qiROtZH2lRiz+R9oP56K8K",
	"ydMVfOEQZYuEMYn6n4UwjM28RCUcv1ELuvV2xC/ZRNSippixEklNsJWiXnRddS/pDtApr1HDl4xxDoki",
	"Jy4n1FyGxljCCDThNaRsiZNZ4pfXbwikeQoytuPV8FNBj5FydNAYtBq0ScHKOUylzZhgwJx3KpCKsrTX",
	"o420iYd9hAtPExhIa3dgoLGR2VIN/fM13JahxgV0DcfTmJETgDNls0a4bhywxn1O0PgIERuM6BT2S0mb",
	"8llij69xxoz9TGIph4gpQZCXxpUmgglKjXFTFimHgjS+QRr3SGuY7IPybSt3E3J/EmqwJhH4ZpUO8hD7",
	"Uhu3aqHgXcI1jPrp6/IwQWjlzLS5BZfbC4wcedmky7ioWUc4RXgrKx9G1Wg0WpcWa1pDaxvZ6ZvdUZYG",
	"UvFWL+Ljy5MUUJnGoIazI5gavIKBn2KMRmt0cDGHu8tex4sR1tBiHeBkcPR+VytJeOnjHAasoxAxWKPk",
	"9fAOc80JS1fzDIPP2ufjFcAze1YqxS2rJUmQKnr+27fSuASmAZlp4qP5D/WmLdyTcX7co61hc+jBeQKc",
	"ocpsJpDQoiJQPjsa/LTDDlL0dFMazo8Lxt3456zIfXMUH/l5NOKP4pKumIYMpRxMb/hvYo6LrrozOmtt",
	"P8jGuvqvq75amP8sOh4NPj1gRgfFSUEuzeie/Xzy6fX9Z2sFL7CCtxXgE6Rl3ZaVyamo3gRNvFvKZSW5",
	"YrdruSrlprkyLmT6pgqurI6lxsMlumX/c8rSPBG231i+aw9l4HGapz6F78I+zvsdi4l+93r+naSpe2XR",
	"66onzufDBVfE6K4XRb433JfHw/4+8ag89s8fEsiTeTrS31klH5jcr2FDfX1T531953v6FvZobR+5ef3I",
	"hd0a57s1zh/01vBiqYD3pRVBkprcV4uz5VdMjx6TedpWLbZqsT1mb4/Zb6q3L5bb937or0TID5z3/vba",
	"NPMnFDxvT3tb/d7q91a/t/r9tl/adJVIGKcrqe1/Wxbdefd/AAAA///S04i5eB4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
